language: php

php: [5.3, 5.4, 5.5, hhvm]

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  exclude:
    - php: hhvm
      env: SYMFONY_VERSION='2.3.*'
    - php: hhvm
      env: SYMFONY_VERSION='2.5.*@dev'

env:
  - SYMFONY_VERSION='2.3.*'
  - SYMFONY_VERSION='2.4.*'
  - SYMFONY_VERSION='2.5.*@dev'

before_script:
  - composer require -n --no-update symfony/symfony=$SYMFONY_VERSION
  - composer install -n --prefer-source

script: phpunit -v
